// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-9Mpo5jx23GcRFObPmpgl7k2ojCbRrJY',
    appId: '1:617508300827:web:e56088b89d3105078d70be',
    messagingSenderId: '617508300827',
    projectId: 'fruit-hub-b180c',
    authDomain: 'fruit-hub-b180c.firebaseapp.com',
    storageBucket: 'fruit-hub-b180c.firebasestorage.app',
    measurementId: 'G-YDJJEME1QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJCZLEHRrXOtIA3f_NBRK4nrVPxgWZAcI',
    appId: '1:617508300827:android:95c8bb0d7d57e0aa8d70be',
    messagingSenderId: '617508300827',
    projectId: 'fruit-hub-b180c',
    storageBucket: 'fruit-hub-b180c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4WnU6-Dm5JRRuXQ3L3VfhTCDBVpqsvng',
    appId: '1:617508300827:ios:7f0919ed72d7d0b98d70be',
    messagingSenderId: '617508300827',
    projectId: 'fruit-hub-b180c',
    storageBucket: 'fruit-hub-b180c.firebasestorage.app',
    iosBundleId: 'com.example.fruitTestMyself',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4WnU6-Dm5JRRuXQ3L3VfhTCDBVpqsvng',
    appId: '1:617508300827:ios:7f0919ed72d7d0b98d70be',
    messagingSenderId: '617508300827',
    projectId: 'fruit-hub-b180c',
    storageBucket: 'fruit-hub-b180c.firebasestorage.app',
    iosBundleId: 'com.example.fruitTestMyself',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-9Mpo5jx23GcRFObPmpgl7k2ojCbRrJY',
    appId: '1:617508300827:web:8dd8c9eee6eac1988d70be',
    messagingSenderId: '617508300827',
    projectId: 'fruit-hub-b180c',
    authDomain: 'fruit-hub-b180c.firebaseapp.com',
    storageBucket: 'fruit-hub-b180c.firebasestorage.app',
    measurementId: 'G-Q17PH6PBYG',
  );
}
